#!/bin/bash

#Recompile the code
./autogen.sh && ./configure && make

#Wait a few seconds to check that it has compiled without errors
sleep 3

#Run run-contest
cd ./datagrump
./run-contest brandon_and_sam 2>&1